# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: ['main']
    paths:
      - .github/workflows/ci.yaml
      - '*.vue'
      - '**.ts'
      - pnpm-lock.yaml
      - vite.config.js
  pull_request:
    branches: ['main']
    paths:
      - .github/workflows/ci.yaml
      - '*.vue'
      - '**.ts'
      - pnpm-lock.yaml
      - vite.config.js

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Detect package manager
        uses: g1eny0ung/detect-nodejs-package-manager-action@v1
        with:
          env-name: pm
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: $pm install
      - run: $pm build
      - run: $pm test
